---
title: Your awesome title
timezone: UTC
collections:
  categories:
    title: Categories
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: project
    status:
    location:
    budget:
    year:
    Categories:
    -
    image:
    images:
    -
- scope:
    path: ''
    type: home carousel
  values:
    image:
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl:
url: http://genex.siteleaf.net/
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
remote_theme: alexandreaco/genex_theme
plugins:
- jekyll-feed
- jekyll-remote-theme
